### ISSUE TITLE
Machine translation

### ISSUE THREAD

**Issue by ThierryCantin-Demers** [ThierryCantin-Demers/tr-and-slate-or#6]
- [ ] [Figure out how to store machine translations in the code](https://github.com/ThierryCantin-Demers/tr-and-slate-or/issues/5)
- [ ] [Support for machine translation](https://github.com/ThierryCantin-Demers/tr-and-slate-or/issues/3)
- [ ] [Support for DeepL API](https://github.com/ThierryCantin-Demers/tr-and-slate-or/issues/2)
- [ ] [Support for Google Translation Cloud API](https://github.com/ThierryCantin-Demers/tr-and-slate-or/issues/4)
